% VerifyGaussInv Tests the GaussianInv function for correctness.
%   This script compares GaussianInv to MATLAB's built-in inv across several
%   randomly generated and specific matrices. It also checks that the
%   function returns empty for singular matrices.
%
%   Usage:
%       Run this script in MATLAB. It prints pass/fail status for each test
%       and a final summary.
%
%   Author: Generated by AI Assistant

clear; clc;

TOL = 1e-10;

% ---------------------------- Test Matrices -----------------------------
rng(123); % Reproducibility

% 1. Random invertible matrices (ensure non-singular by adding n*I)
randInvTests = cell(1,5);
for k = 1:5
    n = randi([2,6]);
    R = randn(n);
    % Shift eigenvalues to avoid near-singularity
    R = R + n*eye(n);
    randInvTests{k} = R;
end

% 2. Singular matrices
singularTests = {
    [1 2 3; 2 4 6; 3 6 9], ...        % linearly dependent rows
    diag([1 0 3]), ...                 % zero on diagonal -> det 0
    randn(4,2)*randn(2,4)              % rank-deficient random 4x4
};

% 3. Identity matrix
identityTest = {eye(4)};

allTests = [randInvTests, identityTest, singularTests];

% ---------------------------- Run Tests ---------------------------------
pass = true;
for k = 1:numel(allTests)
    A = allTests{k};
    n = size(A,1);

    % Determine singularity using matrix rank
    expectedSingular = (rank(A, TOL) < n);
    if ~expectedSingular
        expectedInv = inv(A);
    end

    computedInv = GaussInv(A);

    if expectedSingular
        if isempty(computedInv)
            fprintf('Test %d PASSED (singular matrix handled)\n', k);
        else
            fprintf('Test %d FAILED (expected empty for singular)\n', k);
            pass = false;
        end
    else
        diff = max(abs(expectedInv(:) - computedInv(:)));
        if diff < TOL
            fprintf('Test %d PASSED (diff = %.2e)\n', k, diff);
        else
            fprintf('Test %d FAILED (diff = %.2e)\n', k, diff);
            pass = false;
        end
    end
end

% ------------------------- Summary Report -------------------------------
if pass
    fprintf('\nAll GaussInv tests PASSED within tolerance %.1e!\n', TOL);
else
    error('Some GaussInv tests FAILED. Review implementation.');
end
