% VerifyGaussEqualityOpt Tests GaussEqualityOpt across scenarios.
%   Scenarios:
%     1) Infeasible system
%     2) Unbounded objective
%     3) Constant objective value (multiple solutions)
%
%   Author: Generated by AI Assistant

clear; clc;
TOL = 1e-10;
pass = true;

%% 1) Infeasible system
A1 = [1 1; 1 1];
b1 = [1; 2];
c1 = [1; 1];
[val1, x1, d1] = GaussEqualityOpt(c1, A1, b1);
if isempty(val1) && isempty(x1) && isempty(d1)
    fprintf('Infeasible test PASSED\n');
else
    fprintf('Infeasible test FAILED\n');
    pass = false;
end

%% 2) Unbounded objective
% Constraint x1 - x2 = 0  (so x = (t,t)). Objective maximise x1.
A2 = [1 -1];
b2 = 0;
c2 = [1; 0];
[val2, x2, d2] = GaussEqualityOpt(c2, A2, b2);
if isinf(val2) && ~isempty(x2) && ~isempty(d2) && c2'*d2 > TOL
    fprintf('Unbounded test PASSED\n');
else
    fprintf('Unbounded test FAILED\n');
    pass = false;
end

%% 3) Constant objective (bounded but not unique)
% Constraint x1 = 1; free variable x2. Objective c^T x = x1 (constant 1).
A3 = [1 0];
b3 = 1;
c3 = [1; 0];
[val3, x3, d3] = GaussEqualityOpt(c3, A3, b3);
if abs(val3 - 1) < TOL && max(abs(A3*x3 - b3)) < TOL && max(abs(c3'*d3)) < TOL
    fprintf('Constant objective test PASSED\n');
else
    fprintf('Constant objective test FAILED\n');
    pass = false;
end

%% 4) Random high-dimensional UNBOUNDED case
rng(2024);
for trial = 1:5
    m = 3 + trial;   % 4..8
    n = m + 2;       % underdetermined
    A4 = randn(m, n);
    % Ensure full row rank
    while rank(A4) < m
        A4 = randn(m, n);
    end
    % Build a feasible point x0 and RHS
    x0 = randn(n,1);
    b4 = A4 * x0;
    % Compute nullspace basis
    N4 = null(A4, 'r');
    dirPos = N4(:,1);           % pick first direction
    c4 = dirPos;                % objective aligns with direction -> unbounded
    [val4, x4, d4] = GaussEqualityOpt(c4, A4, b4);
    if isinf(val4) && c4' * d4 > TOL && max(abs(A4*x4 - b4)) < TOL
        fprintf('Random unbounded test %d PASSED\n', trial);
    else
        fprintf('Random unbounded test %d FAILED\n', trial);
        pass = false;
    end
end

%% 5) Random high-dimensional CONSTANT OBJ case
for trial = 1:5
    m = 4 + trial;   % 5..9
    n = m + 3;       % underdetermined
    A5 = randn(m, n);
    while rank(A5) < m
        A5 = randn(m, n);
    end
    x0 = randn(n,1);
    b5 = A5 * x0;
    % Choose c in row-space of A: c = A' * y
    y = randn(m,1);
    c5 = A5' * y;
    [val5, x5, d5] = GaussEqualityOpt(c5, A5, b5);
    if ~isinf(val5) && abs(val5 - c5' * x0) < TOL && max(abs(c5' * d5)) < TOL
        fprintf('Random constant-objective test %d PASSED\n', trial);
    else
        fprintf('Random constant-objective test %d FAILED\n', trial);
        pass = false;
    end
end

%% 6) Random INFEASIBLE case (higher dimension)
for trial = 1:5
    n = 3 + trial;    % variables 4..8
    % Build full column rank square part
    A_sq = randn(n,n);
    while rank(A_sq) < n
        A_sq = randn(n,n);
    end
    x0 = randn(n,1);
    b_sq = A_sq * x0;

    % Add an extra independent equation that makes system inconsistent
    extra_row = randn(1, n);
    % Ensure extra_row not in row span; quickly retry
    % while rank([A_sq; extra_row]) == n
    %     extra_row = randn(1, n);
    % end
    b_extra = extra_row * x0 + 1;  % offset ensures inconsistency

    A6 = [A_sq; extra_row];
    b6 = [b_sq; b_extra];
    c6 = randn(n,1);

    [val6, x6, d6] = GaussEqualityOpt(c6, A6, b6);
    if isempty(val6) && isempty(x6) && isempty(d6)
        fprintf('Random infeasible test %d PASSED\n', trial);
    else
        fprintf('Random infeasible test %d FAILED\n', trial);
        pass = false;
    end
end

%% Summary
if pass
    fprintf('\nAll GaussEqualityOpt tests PASSED!\n');
else
    error('Some GaussEqualityOpt tests FAILED.');
end
