% VerifyGaussLinearSystem Tests GaussLinearSystem solver across cases.
%   The script covers:
%     1) Infeasible system (no solution)
%     2) Unique solution (square, full-rank)
%     3) Underdetermined system (infinitely many solutions)
%
%   For each case, the script validates that the returned solution meets
%   feasibility requirements (Ax = b) or produces empty when infeasible.
%
%   Author: Generated by AI Assistant

clear; clc;
TOL = 1e-10;
pass = true;

%% 1) Infeasible system
A1 = [1 1; 1 1];
b1 = [1; 2]; % Inconsistent
x1 = GaussLinearSystem(A1, b1);
if isempty(x1)
    fprintf('Infeasible system test PASSED (returned empty)\n');
else
    fprintf('Infeasible system test FAILED (expected empty)\n');
    pass = false;
end

%% 2) Unique solution
A2 = [3 -1; 2 4];
b2 = [7; 10];
true_x2 = A2\b2; % MATLAB backslash for reference
x2 = GaussLinearSystem(A2, b2);
if ~isempty(x2) && max(abs(A2*x2 - b2)) < TOL
    fprintf('Unique solution test PASSED (solution feasible)\n');
else
    fprintf('Unique solution test FAILED\n');
    pass = false;
end

%% 3) Underdetermined system (many solutions)
A3 = [1 2 3; 4 5 6];
b3 = [14; 32];
% Note: infinite solutions exist; check feasibility only
x3 = GaussLinearSystem(A3, b3);
if ~isempty(x3) && max(abs(A3*x3 - b3)) < TOL
    fprintf('Underdetermined system test PASSED (returned feasible solution)\n');
else
    fprintf('Underdetermined system test FAILED\n');
    pass = false;
end

%% 4) Random larger full-rank square systems (unique solutions)
rng(2024);
for n = 3:8
    A_rand = randn(n);
    % Ensure full rank by adding n*I (well-conditioned)
    A_rand = A_rand + n*eye(n);
    b_rand = randn(n,1);
    x_rand = GaussLinearSystem(A_rand, b_rand);
    if ~isempty(x_rand) && max(abs(A_rand*x_rand - b_rand)) < TOL
        fprintf('Random square %dx%d test PASSED\n', n, n);
    else
        fprintf('Random square %dx%d test FAILED\n', n, n);
        pass = false;
    end
end

%% 5) Random larger underdetermined systems (many solutions)
for m = 40:20:80
    n = m + 3; % more columns than rows
    A_ud = randn(m, n);
    b_ud = randn(m, 1);
    x_ud = GaussLinearSystem(A_ud, b_ud);
    if ~isempty(x_ud) && max(abs(A_ud*x_ud - b_ud)) < TOL
        fprintf('Random underdetermined %dx%d test PASSED\n', m, n);
    else
        fprintf('Random underdetermined %dx%d test FAILED\n', m, n);
        pass = false;
    end
end

%% 6) Random inconsistent systems (infeasible)
for m = 40:20:80
    n = m; % square
    A_in = randn(m, n);
    b_in = randn(m,1);
    % Force inconsistency by replacing last row with zeros, rhs non-zero
    A_in(end,:) = 0;
    b_in(end) = 1;
    x_in = GaussLinearSystem(A_in, b_in);
    if isempty(x_in)
        fprintf('Random infeasible %dx%d test PASSED (returned empty)\n', m, n);
    else
        fprintf('Random infeasible %dx%d test FAILED (expected empty)\n', m, n);
        pass = false;
    end
end

%% Summary
if pass
    fprintf('\nAll GaussLinearSystem tests PASSED!\n');
else
    error('Some GaussLinearSystem tests FAILED.');
end
