% VerifyGaussRREF Tests the GaussRREF function for correctness.
%   This script compares the output of GaussRREF with MATLAB's built-in rref
%   across several test matrices. A small numerical tolerance is used to
%   account for floating-point arithmetic.
%
%   Usage:
%       Run this script in MATLAB. It will display test results and a
%       summary indicating whether all tests passed.
%
%   Author: Generated by AI Assistant

% Clear workspace for clean testing environment
clear; clc;

% Tolerance for comparison
TOL = 1e-10;

% ----------------------------- Test Matrices -----------------------------
% 1. Random matrices of various sizes
rng(42); % For reproducibility
randomTests = arrayfun(@(~) randn(randi([2,6]), randi([2,6])), 1:5, 'UniformOutput', false); %Commented  xhj

% 2. Singular matrix
singularTest = {[1 2 3; 2 4 6; 3 6 9]};

% 3. Rectangular fat matrix
fatTest = {[1 3 2 4; 2 6 4 8]};

% 4. Rectangular tall matrix
tallTest = {[1 2; 3 4; 5 6]};

% Combine all tests
allTests = [randomTests, singularTest, fatTest, tallTest];

% ---------------------------- Test Execution -----------------------------
pass = true;
for k = 1:numel(allTests)
    A = allTests{k};
    R_expected = rref(A);
    R_actual   = GaussRREF(A);
    diff = max(abs(R_expected(:) - R_actual(:)));
    if diff < TOL
        fprintf('Test %d PASSED (diff = %.2e)\n', k, diff);
    else
        fprintf('Test %d FAILED (diff = %.2e)\n', k, diff);
        pass = false;
    end
end

% ----------------------------- Final Report ------------------------------
if pass
    fprintf('\nAll tests PASSED! GaussRREF is consistent with rref within tolerance %.1e.\n', TOL);
else
    error('Some tests FAILED. Review GaussRREF implementation.');
end
